### PR TITLE
Rework #790 to define newscr in tig.h if undefined

### PR DESCRIPTION
**Pull request by jonas**

### CODE REVIEW

**Comment by jonas** [comment]
@rofl0r Would it be possible for you to test this? I can merge if that makes it easier.

**Comment by rofl0r** [comment]
that looks as if it would work, but i can test it later. why do you think this change is needed ? was there a regression ?

**Comment by rofl0r** [comment]
```
src/tig.c: In function 'parse_options':
src/tig.c:517:21: error: #if with no expression
 #if NCURSES_WIDECHAR
                     ^
```
i suppose this should be `#if NCURSES_WIDECHAR+0`

**Comment by jonas** [comment]
Thanks for testing this @rofl0r

**Pull request merged**
