### PR TITLE
Added word-diff=plain colorizing support

### LINKED ISSUE #221: --word-diff
Hi, I've just discover the amazing --world-diff options, which diff by world instead of line.
It works with git show and git diff.
I would like to be my default diff method, but I can't make it work.
I  tried to set TIG_DIFF_OPTS but it doesn't work.

Also, when I try
tig show --word-diff, it doesn't display the colors :-(

### PR DESCRIPTION
**Pull request by dvalter**
Added ADD and DEL colors for {+added+} and [-removed-] blocks of git word-diff=plain

Since git does not escape delimiters in word-diff, this code may produce an incorrect color output on some code that actually contains these sequences including the first commit of this PR.

It's possible to bypass this by using git color escape sequences to determine additions and deletions, but it's likely to conflict with the rest of diff parser.

(Probably) fixes #221

### CODE REVIEW

**Comment by eMPee584** [comment]
.. hey @koutcher, can you please have a look at this? :cowboy_hat_face:

**Comment by koutcher** [comment]
The proper way to do this would involve `--word-diff=porcelain` (see #47) but I understand it would require much more rework of the parser, so this is an interesting step already. There is a problem when hovering the cursor line over empty lines (j,k) as they remain highlighted.

**Comment by dvalter** [comment]
@koutcher I definitely missed that during my previous testing. It should be fixed now.

**Comment by koutcher** [comment]
What is the purpose of LINE_WDIFF_PLAIN ?

**Comment by dvalter** [comment]
I feel like since the line is parsed and colorized, it's not *default* anymore. Now it should not have an impact, but it may help in further development.
If that's not right, I'll remove LINE_WDIFF_PLAIN.

**Comment by koutcher** [comment]
The line type is normally attached to a color line in tigrc so it wouldn't bring anything here. There was a better way to solve the cursor line problem (just change the last parameter of diff_common_add_cell to true) so I merged 9b9e6f2 and did a few adjustments to ensure it will be  transparent for people not using word diff. You can have a look to https://github.com/koutcher/tig/commit/41763ae3c1516004ccc32da79d64363a86a861be before I push it to jonas/tig.

**Comment by dvalter** [comment]
> The line type is normally attached to a color line in tigrc so it wouldn't bring anything here

There's an alternative use case regarding key handling (i.e. DIFF_STAT), so I thought it may make sense if some action for diff add/del will be added.

>You can have a look to koutcher@41763ae before I push it to jonas/tig.

It's absolutely fine. I love that you've added a word-diff CLI argument switch, it was definitely needed there.

**Comment by koutcher** [comment]
Point taken for the line type, we can introduce later is there is a need for a specific action. Thanks for this contribution!

**Comment by vivien** [comment]
When I use `tig --word-diff=plain`, the changes are shown like `[-classic-]{+strict+}`. Am I missing something?

**Comment by dvalter** [comment]
> When I use `tig --word-diff=plain`, the changes are shown like `[-classic-]{+strict+}`. Am I missing something?

It's an intended behavior, if they have DEL and ADD colors respectively. It should look basically like an output of `git show --word-diff=plain`.
Screenshot_2020-06-10_22-14-42
Screenshot_2020-06-10_22-15-35

Stripping them is not viable as it will break commits like 4028a495425.

**Pull request closed without merging**
