### PR TITLE
Can change default tigrc on make

### PR DESCRIPTION
**Pull request by spk**
This allow to change the default tigrc path on make with:

```
TIG_USER_CONFIG='~/.config/tig/rc' make
```

Cheers

### CODE REVIEW

**Comment by jonas** [comment]
Can you give me the motivation to add this when it is already possible to:

    export TIGRC_USER=~/.config/tig/rc

**Comment by spk** [comment]
To avoid to set this environment, feel free to close this PR if you don't find this useful

**Comment by jonas** [comment]
OK makes sense.

**Comment by jonas** [comment]
Thanks for the patch.

**Comment by spk** [comment]
Thanks for this nice application.

**Pull request closed without merging**
