### PR TITLE
Add A as a binding to apply a stash without dropping it.

### PR DESCRIPTION
**Pull request by parkercoates**
Pretty straight forward.

### CODE REVIEW

**Comment by parkercoates** [comment]
Okay, this commit changes the contents of the help screen output, since a new binding has been added. This breaks the tests on the help output. Is the expectation that I manually update the samples used in the help tests, or is there a fancy process for such changes?

**Comment by jonas** [comment]
@parkercoates If you rebase on top of current `master` you should be able to run this command to update the expected test output

```bash
make test/help/all-keybindings-test && \
  cp test/tmp/help/all-keybindings-test/help-default.screen test/help/all-keybindings-test.expected
```

**Comment by jonas** [comment]
OK, ended up merging and fixing the test myself. Thanks for the contribution and suggestion to easily allow the expected output to be updated.

**Comment by parkercoates** [comment]
That's the real trick to open source. ;) Offer a one line pull request, then sit back and watch as it prompts the reviewer into writing an additional 130 lines of supporting changes!

Thank you very much!

**Pull request closed without merging**
