### PR TITLE
Turn on '--follow' if 'log.follow' is set to true in git config

### PR DESCRIPTION
**Pull request by duncanmak**
This is a tiny patch that address #881

### CODE REVIEW

**Comment by duncanmak** [comment]
I don't know why the AppVeyor build failed, the tests passed on my local machine. It'd be nice to retrigger a build, perhaps it's just a glitch.

**Comment by koutcher** [comment]
`git log --follow` is only accepted with a pathspec, so, with this patch, any attempt to start tig without argument while log.follow is set to true in git config will fail. This is not reflected by the test suite because log.follow is never set, so this is not the reason for the AppVeyor build to fail.

**Comment by duncanmak** [comment]
@koutcher Yes, you're totally right. I realized the same thing last night.

Do you know of a way to check that `tig` is being asked to load a `pathspec` and not a directory/repo?

**Comment by koutcher** [comment]
I believe the test `opt_file_args && !opt_file_args[1]` should ensure there is one pathspec and only one. 

Though forcing —follow argument could do the job it would be interesting to understand why it works as the log.follow set to true in git config already makes git log to behave as git log —follow. There must be something else inside tig induced by the presence of the —follow which maybe could be trigged when log.follow is true.

**Comment by duncanmak** [comment]
@koutcher Thanks for the tip and I have pushed a new commit. I believe the behavior is more correct now.

The reason why `--follow` is needed is because it turns off the graph rendering.  Without it, the graph will render and the lines veer off to the right.

With `log.follow` enabled (but no patch):

image

With `--follow` (no patch):

image
So this patch is simply to show the `--follow` behavior automatically when `log.follow` is turned on and we're viewing a single file.

P.S. Perhaps `with_graph` should always be `false` when we're only viewing a single file?

**Comment by jonas** [comment]
Git has support for rewriting the history when filtering, this is enabled by the `git log --parents` flag:

```
/opt/tig@master > git log --parents src/tig.c | grep ^commit | head -3
commit a7eb2a3a8b188388c0eb2c6fe476990ad83c7fed 2272096ce3dccc3622c7f095a67005d405be2e9c
commit 2272096ce3dccc3622c7f095a67005d405be2e9c ccbda97bda65810cd416b5b4fbf7127c2e0aa951
commit ccbda97bda65810cd416b5b4fbf7127c2e0aa951 71e8361184fb19845e65fdd06538948a5376ccbf
/opt/tig@master > git log --follow --parents src/tig.c | grep ^commit | head -3
commit a7eb2a3a8b188388c0eb2c6fe476990ad83c7fed 2272096ce3dccc3622c7f095a67005d405be2e9c
commit 2272096ce3dccc3622c7f095a67005d405be2e9c d74e28a89959e3ed949bac32a21a5cc72de37554
commit ccbda97bda65810cd416b5b4fbf7127c2e0aa951 71e8361184fb19845e65fdd06538948a5376ccbf
/opt/tig@master > git -c log.follow=true log --parents src/tig.c | grep ^commit | head -3
commit a7eb2a3a8b188388c0eb2c6fe476990ad83c7fed 2272096ce3dccc3622c7f095a67005d405be2e9c
commit 2272096ce3dccc3622c7f095a67005d405be2e9c d74e28a89959e3ed949bac32a21a5cc72de37554
commit ccbda97bda65810cd416b5b4fbf7127c2e0aa951 71e8361184fb19845e65fdd06538948a5376ccbf
```
History rewriting is disabled when `--follow` is passed or `log.follow` is enabled and **a single path is given** according to the `git-config` man page:

> `log.follow`
>           If true, git log will act as if the --follow option was used when a single <path> is given. This has the same limitations as --follow, i.e. it cannot be used to follow multiple files and does not work well on non-linear history.

It sounds like we have to introduce a global variable for tracking the `log.follow` option and use it for automatically enabling/disabling the graph. This could be done in addition to the existing `no_graph` check in `src/argv.c:argv_parse_rev_flag`.

**Comment by koutcher** [comment]
As suggested by @duncanmak in his P.S., maybe the graph does not make sense when pathspec is specified. Could be done just by adding `&& !opt_file_args` in src/main.c:main_with_graph. 

Using tig --author=... the other day, I wondered also if it shouldn't be without graph as well.

**Comment by jonas** [comment]
History rewriting works for a single file, but I agree that a linear graph is not useful. I am okay with disabling the graph in this case.

And yes, it might make sense to disable the graph entirely for author searches. Another option would be to dynamically try to detect fragmented graphs and redraw them.

**Comment by koutcher** [comment]
Disabling the graph when a pathspec is specified is finally too aggressive as history rewriting works quite well most of the time. The monorepo addicts will hate it. 

Switching to tracking the log.follow option to disable the graph.

**Pull request closed without merging**
