### PR TITLE
stub docs for testing API

### PR DESCRIPTION
**Pull request by rolandwalker**
`test_setup()` doesn't look like it is meant to be exposed, but is called by `gh-490-heap-buffer-overflow-test`.

### CODE REVIEW

**Comment by jonas** [comment]
Very good idea, I'll try to see if I can fill it out. `test_setup` is there to exit quickly in the test, we might be able to remove if we add an `exit 0` call in `test_skip`.

**Comment by jonas** [comment]
To make this manageable I suggest to embed the documentation into `libtest.sh` and `libgit.sh` using docstrings and have a small too that extracts them to `test/api.md`.

Something like
```sh
## Run tig in test mode
#
# Setup a controlled environment and report the test result.
#
# Input to be procssed via stdin is passed and stderr is captured and
# can be used for later assertions.
#
# ```sh
# test_tig show 1a2b3c4d5e6f
# ```
test_tig()
{
...
```

Which would become:

```markdown
## test_tig: Run tig in test mode

Setup a controlled environment and report the test result.

Input to be procssed via stdin is passed and stderr is captured and
can be used for later assertions.

```sh
test_tig show 1a2b3c4d5e6f
`` `
```

**Comment by rolandwalker** [comment]
Yes good idea.

**Comment by rolandwalker** [comment]
reimplemented as `make test/API.adoc`

**Comment by jonas** [comment]
Thanks

**Pull request merged**
