### PR TITLE
Add chocolate theme

### PR DESCRIPTION
**Pull request by edi9999**
I haven't seen any other themes in the repository, here is how it looks like : 

selection_017

I'm not sure if it is possible to colorize the commit messages, but if it is I'd like to colorize them a little bit.

Hope you enjoy it

### CODE REVIEW

**Comment by jonas** [comment]
Thanks for the theme. The text in the `main` view can be coloured by setting `main.default`:

    color main.default yellow default

**Comment by vivien** [comment]
Great! I can't wait to see a `contrib/solarized.tigrc` theme from @altercation too :-P

**Comment by annata83** [comment]
where can I customize the colors?

**Comment by koutcher** [comment]
See https://github.com/jonas/tig/blob/master/doc/tigrc.5.adoc

**Comment by annata83** [comment]
@koutcher  Thanks

**Comment by annata83** [comment]
Cannot figure it out how to change the status line color; I am using it as follows:

`color status	white	black bold`

What am I missing?

**Comment by koutcher** [comment]
Maybe you are looking for title-focus / title-blur instead of status ?

**Pull request merged**
