### PR TITLE
save/restore TTY attributes in test suite

### PR DESCRIPTION
**Pull request by rolandwalker**
defending against a tig crash

### CODE REVIEW

**Comment by jonas** [comment]
What's the motivation for this? Tests are not supposed to touch the TTY.

**Comment by rolandwalker** [comment]
I believe the motivation is fairly covered in https://github.com/jonas/tig/pull/725#discussion_r142008745, but even without #725, there were some cases where a tig crash during tests left the TTY in a wrong state.

Ncurses may do some unexpected things to resolve conflicts: *eg* tig gives ncurses `/dev/null` for the third argument to `newterm()`, but then tig calls `raw()` and so on.  And `raw()` must call `ioctl()`, which is only possible on an fd which refers to a device or special file (tty).  `raw()` might be returning `ENOTTY` and we fail to check the return value.

But in at least some cases it seems that ncurses decides to muddle through with some undefined behavior.  For example it switches to STDIN for `wgetch()` after being told that `infd` referred to `/dev/null`.

That is from memory, and I don't have the code in front of me, so some details may be wrong.

Feel free to decline the PR — it is just a bit of defensive driving.  The explanation is for your interest.

**Comment by jonas** [comment]
Ah, OK. Thanks for the explanation. Makes sense.

**Pull request merged**
