### PR TITLE
Add support of toggling commit and author (name and date)

### PR DESCRIPTION
**Pull request by PaulChanHK**
Add support of toggling commit and author (name and date)

i.e. toggling of:
1. author and committer (toggle option=m)
2. author-date and commit-date (toggle option=M)

Currently, applicable to view: main, log, refs, blame and tree.

### CODE REVIEW

**Comment by neeels** [comment]
Tried this PR, rebased onto current upstream master, and noticed:

The 'm' shortcut is set for toggling the commit-date. It doesn't work, because m is already bound to 'main view'. 'M' doesn't work either, it says "Unknown key". Or I misunderstood that part.

When I'm in a help screen and issue the toggle then, and then exit the help screen, the dates have not toggled, and even though e.g. commit-date = no I'm still seeing the commit date. When I issue the toggle in the main view though the dates immediately change properly.

In the :h help screen the commit-date and committer options are not described.

It would be helpful if the commit log message(s) would say what config options have been added, so one doesn't need to parse the code to find out how to use the feature.

Commit 9bbe is just a comment tweak, but the commit log says something completely different.

**Comment by PaulChanHK** [comment]
Add support of toggling commit and author (name and date)

    1. author name and committer name, toggle option=m
    2. author-date and commit-date, toggle option=M
    This is effective in views: main, log, refs, blame and tree.

image

**Comment by PaulChanHK** [comment]
> 
> 
> Tried this PR, rebased onto current upstream master, and noticed:
> 
> The 'm' shortcut is set for toggling the commit-date. It doesn't work, because m is already bound to 'main view'. 'M' doesn't work either, it says "Unknown key". Or I misunderstood that part.
> 
> When I'm in a help screen and issue the toggle then, and then exit the help screen, the dates have not toggled, and even though e.g. commit-date = no I'm still seeing the commit date. When I issue the toggle in the main view though the dates immediately change properly.
> 
> In the :h help screen the commit-date and committer options are not described.
> 
> It would be helpful if the commit log message(s) would say what config options have been added, so one doesn't need to parse the code to find out how to use the feature.
> 
> Commit 9bbe is just a comment tweak, but the commit log says something completely different.

# It have been working - You can access the "toggle options menu" by key 'o' and use L/R arrow keys to switch between the toggle options.
# New PR added an error when the Committer/Author are not effective in some views like stage view and diff view.
# The author did not add the "options menu" to the help, submitted another PR.

**Comment by chirayuk** [comment]
This may no longer be required now that https://github.com/jonas/tig/commit/7351f170b0e4e6f7675ccff9167b4892ed9f426b has been merged to master.

**Pull request closed without merging**
