### PR TITLE
Introduce reflog view

### LINKED ISSUE #538: [RFE] add `git reflog` information to tig
It would be great if I could see the reflog in tig and browse those commits. I use `git reflog` [sometimes](https://kparal.wordpress.com/2011/09/01/git-tip-of-the-day-recover-lost-commits/) to recover commits that no longer are being pointed to by some other ref.

If this feature is already there and I missed it, I apologize.

### PR DESCRIPTION
**Pull request by koutcher**
Press L to open the reflog view or start with tig reflog.

The main benefit over git reflog --pretty=raw | tig --pretty=raw
is the ability to browse the full chain of commits for each reflog.

Closes #538

### CODE REVIEW

**Comment by gipsy-king** [comment]
Cool, I was just looking for this in the issues and found this here. Tried locally, it works!

Would it make sense to add `bind reflog    C       ?git checkout %(branch)` to `tigrc`? That is my main use case, but I don't know for what purpose other people use `git reflog` mainly. Then also `%(branch)` is not ideal, when going through rebases etc., you might want to checkout a commit instead. But there doesn't seem to be a `branch or fallback to commit` available in `tigrc`.

**Comment by koutcher** [comment]
It is quite unlikely that you want to do a `checkout %(branch)` from the reflog because if your commit is reachable with an actual ref, you shouldn't need the reflog. 

The most typical use cases would be `cherry-pick` to recover a single commit or `reset` to undo a rebase for example. 

There is already a binding for cherry pick in the main view and I added a `!` binding to the reflog view for `reset --hard`.

**Comment by gipsy-king** [comment]
Sounds good. I can always add it to my `tigrc`.

**Comment by koutcher** [comment]
I figured out your use case, `bind reflog C ?git checkout %(branch)` added to tigrc.

**Comment by gipsy-king** [comment]
Wow, thanks ;)

**Pull request merged**
