### PR TITLE
Fix diff highlighting of removed lines starting with -- and added lines starting with ++

### LINKED ISSUE #875: tig diff messed up if a line starting with `--foo` is removed in diff
git clone https://github.com/nim-lang/Nim
cd Nim
tig 08de33a2e38b8bf859276dbf2d4c1eda87b6a459

image

git show 08de33a2e38b8bf859276dbf2d4c1eda87b6a459

image

as you can see the `---path:"../compiler"` is in blue (same color as `define:nimcore` ) instead of red

### PR DESCRIPTION
**Pull request by koutcher**
When working with Ada source code (where comments start with --), the diff highlighting is messed up whenever a comment starting at the beginning of the line is removed because tig takes it either for the DEL_FILE or the START prefix.

 It should close #875 and #871.

Added more changes closing #804, #762 and #866.

### CODE REVIEW

**Comment by jonas** [comment]
Wow, thanks a lot Thomas!

**Comment by odnoletkov** [comment]
There is `status.showUntrackedFiles` Git config option (and corresponding command line options) allowing to override default behavior and say don't show untracked files at all. It is useful for some repositories and some use-cases (like partially tracking home directory). Instead of having a separate option in tig can we read if from the Git configuration to avoid having to duplicate this configuration?

**Comment by jonas** [comment]
Yes, that's a good idea. Let's do that. Do you want to do a follow-up or should I do it?

**Comment by jonas** [comment]
Actually, I will have to read the documentation for the option. Currently, Tig shows untracked files by default in the main view. Not sure if it is confusing to have a "status.*" Git option apply to Tig's main view

**Pull request merged**
