### PR TITLE
Add zsh completion file for autoload

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by wkentaro** [comment]
Moved from https://github.com/Homebrew/homebrew/pull/43320

**Comment by aemonge** [comment]
+1

**Comment by jonas** [comment]
@wkentaro Thanks. I suggest that the file is renamed to `contrib/tig-completion.zsh`. I can do this if you prefer.

**Comment by wkentaro** [comment]
In that case, the completion file should be renamed to `_tig` at installation.
Where can I find the code which installs the completion files? (`make install-doc` seems not)

**Comment by jonas** [comment]
The completion files are not currently installed. I suggest putting that information in the file header and then publishing a patch to Homebrew adding a line after the [bash completion install](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/tig.rb#L34) using [zsh_completion.install](https://github.com/Homebrew/homebrew/blob/8ba134eda537d2cee7daa7ebdd9f728389d9c53e/Library/Formula/gibo.rb#L10).

**Comment by wkentaro** [comment]
Okay, updated.

**Comment by jonas** [comment]
Thanks

**Pull request merged**
