### PR TITLE
completion: Simple rewrite attempt

### PR DESCRIPTION
**Pull request by lbonn**
Work towards #540.

I made a small completion script which re-uses the base git's. It is supposed to have better support for revisions and options completions.

The drawback is that the base git's completion must be installed beforehand. For most bash users, this should be a given. For zsh, it would probably won't work in this state but tig's completion is already builtin in zsh (see [git's completion in zsh's tree](https://sourceforge.net/p/zsh/code/ci/master/tree/Completion/Unix/Command/_git)). It only matches `git log` behaviour though...

It should also be checked for compatibility with old git versions. Does tig have a minimum git version requirement?

A standalone version should not be too hard to write with heavy copy-pasting if needed.

Either way, this first draft can be used to validate its correct behaviour. I tried some common combinations but additional testing would be nice.

### CODE REVIEW

**Comment by jonas** [comment]
Cool, I was not able to get the `_completion_loader` working on mac os x. Will take a closer look when I get more time.

I have one suggestion to improve blame completion to also match revisions:

```
diff --git i/contrib/tig-completion.bash w/contrib/tig-completion.bash
index a40088c..deba0cb 100755
--- i/contrib/tig-completion.bash
+++ w/contrib/tig-completion.bash
@@ -29,9 +29,10 @@
 
 __tig_cmds="blame status show log stash grep"
 
-__tig_complete_revlist_or_cmd ()
+__tig_complete_revlist_or_list ()
 {
 	local pfx ls ref cur_="$cur"
+	local list="$1"
 	case "$cur_" in
 	*..?*:*)
 		return
@@ -83,7 +84,7 @@ __tig_complete_revlist_or_cmd ()
 		__gitcomp_nl "$(__git_refs)" "$pfx" "$cur_"
 		;;
 	*)
-		__gitcomp "$__tig_cmds"
+		__gitcomp "$list"
 		__gitcomp_nl_append "$(__git_refs)"
 		;;
 	esac
@@ -118,7 +119,7 @@ _tig ()
 			__gitcomp "-v -h"
 			;;
 		*)
-			__tig_complete_revlist_or_cmd ;;
+			__tig_complete_revlist_or_list "$__tig_cmds" ;;
 		esac
 		return
 	fi
@@ -131,7 +132,7 @@ _tig ()
 	status)
 		_git_status;;
 	blame)
-		__gitcomp "$(__git_complete_file)";;
+		__tig_complete_revlist_or_list "$(__git_complete_file)";;
 	*)
 		_git_log ;;
 	esac
```

**Comment by lbonn** [comment]
About OSX: maybe I overestimated the portability of this approach.

I also tried your patch but if I just type `tig blame <tab><tab>`, I only get a list of refs which is not what I need from blame in most of the cases. It only gives a list of files if the current word does not match any rev (eg: if I have a file `mouse.c` and a branch `master`, only `master` would appear if I type `m<tab>`).

`__git_complete_file` might be the cause, here is its definition along with `__git_complete_revlist` in git-completion.bash.

```
__git_complete_file ()
{
	__git_complete_revlist_file
}

__git_complete_revlist ()
{
	__git_complete_revlist_file
}
```

Apparently this is used to match a revision in priority and only files if none matches, typically for `log`, `diff` for which it is recommended to use `--` to limit to files.

Is it common to supply a revision to tig blame? Even if the completion to files and revs works, having the full list of revs (which can be pretty large in some repos) if the user only seeks files is not really helpful.

But maybe I just don't know about the use cases of `tig blame rev`.

Also, the whole `blame` completion seems to be missing from git's script to let it fall back on bash's default completion to file. But this is probably an argument from authority :).

**Comment by lbonn** [comment]
I put all the mainline completion utilities we depend on directly in the file to avoid being too dependent on the environment and/or git's completion version (just like it was before).

In theory, the inlining could be semi-automatized (with some effort...) to ease the maintenance but we probably don't need to update the completion too often.

The issue you raised about the blame completion still need to be resolved. Personally, I'd still be in favor of using the mainline approach which favors the most common command usage.

**Comment by jonas** [comment]
Thanks, I will install it and test it out next week

**Comment by lbonn** [comment]
News on this?

FWIW, I have been using it almost daily since then.

Noteworthy examples:

    tig ..<tab>  # shows refs on this branch, files on stock completion
    tig master -- <tab>  # shows files on this branch, refs on stock completion

**Pull request closed without merging**
