### PR TITLE
let `set diff-highlight=true` work when the diff-highlight executable is not on $PATH

### PR DESCRIPTION
**Pull request by rolandwalker**
`diff-highlight` lives under contrib and is probably not on the user's `$PATH` in most installs

### CODE REVIEW

**Comment by jonas** [comment]
I played around with this one and I really like the idea how I'd prefer that the lookup does an `lstat` to verify the location of the diff-highlight script. WDYT?

**Comment by rolandwalker** [comment]
Manually finding the location would also have the advantage of being able to invoke `diff-highlight` when the package manager failed to create the executable (at some revision it became required to run `make` in the `…/contrib/diff-highlight` dir).

**Comment by rolandwalker** [comment]
Revised, with probably too much refactor.  Willing to squash as always.

* executing `git --exec-path` was relatively expensive so the result is preserved.  A few other things could realize similar savings.
* due to caching, setting `diff-highlight` multiple times as was done in the tests no longer works.  This is construed as a feature.
* logic about how to invoke the `diff-highlight` utility seems unrelated to viewing diffs, so it was spun out into `apps.c`.  If you don't like a new file, `options.c` would make more sense than `diff.c`.
* The "rescue" scenario started in recent versions of git, and happens to me currently with git from Macports.  The user lacks a shebanged `diff-highlight` executable unless an extra `make` step was done.  But this can be trivially worked around by invoking `perl` directly.  Unfortunately test coverage for this code path doesn't seem possible at the moment.

Handling of`diff-highlight` execution failure wants a few improvements, but was left unchanged.

**Comment by rolandwalker** [comment]
valgrind doesn't like the final test case

**Comment by rolandwalker** [comment]
valgrind issue addressed

**Pull request merged**
