### PR TITLE
Avoiding null pointer dereference

### PR DESCRIPTION
**Pull request by binho1991**
This pull request aims to fix null pointer dereference.

[Null pointer dereference](https://cwe.mitre.org/data/definitions/476.html)

### CODE REVIEW

**Comment by koutcher** [comment]
@jonas, I started to review this PR from @binho1991 and have some suggestions, see https://github.com/koutcher/tig/commit/gh-1096-null-pointer-deref.

**Comment by krobelus** [comment]
there are many other places where allocation can fail. Shouldn't we just use xmalloc/xcalloc like git does?

**Comment by binho1991** [comment]
Hi @koutcher and @krobelus! Does anything still need to be done for the pull request to be accepted? Some points do not use xmalloc/xcalloc. Is there any difference in their use? If need be, I can change the pull request to use xmalloc and xcalloc. Thanks!

**Comment by koutcher** [comment]
@binho1991, thank you, I don't think xmalloc/xcalloc would bring any benefit. You did a pretty good job at identifying the missing checks, only a few remained in argv_append. I completed my review in https://github.com/koutcher/tig/commit/4958efebb6c122745b63a4d5dab12610e28c4f2e (see src/argv.c and src/util.c), I believe it should be enough.

**Comment by binho1991** [comment]
@koutcher thanks for the feedback.

**Pull request merged**
