### PR TITLE
Disable ncurses extended key values so that esc-codes can be used in …

### PR DESCRIPTION
**Pull request by mckellygit**
…mappings for Shift/Ctrl/Alt Up/Dn/Lt/Rt/Hm/En/In/De/PgUp/PgDn

This is the other way to go, as compared to PR https://github.com/jonas/tig/pull/1048

thx,
-m

### CODE REVIEW

**Comment by koutcher** [comment]
Merged manually in aee8eb1.

**Comment by mckellygit** [comment]
@koutcher thx.  Something is weird tho, in my original PR a binding such as:
```
bind generic   <Esc>[1;5B   scroll-line-down
```
worked fine - but now it does not, and I need to use:
```
bind generic   <Ctrl-[>[1;5B   scroll-line-down
```
I will dig into it and post what I find.

**Comment by mckellygit** [comment]
@koutcher its a problem with my other commit that was merged and the values for Esc and C-_
I'll post a PR to fix it asap.

**Comment by mckellygit** [comment]
ok, PR added: https://github.com/jonas/tig/pull/1058

**Comment by koutcher** [comment]
Good catch. I should have spotted that during the review. I was so focussed on the possible side-effect of changing the < in <= that I was happy enough when I checked that CTRL('z') was handled separately and I completely overlooked that when going from 25 to 30, 27 was also invited to the party. Hopefully 28 is only ^\.

**Comment by mckellygit** [comment]
@koutcher @jonas just an fyi - I was working with xaizek on vifm for this same issue and he suggested a cleaner way to solve this.
We added this code -
```
#if defined(NCURSES_EXT_FUNCS) && NCURSES_EXT_FUNCS >= 20081102
	/* Disable 'unsupported' extended keys so that esc-codes will be
	 * received instead of unnamed extended keycode values (> KEY_MAX).
	 * These keys can then be mapped with esc-codes in rc files.
	 * An example could be <c-down>:
	 *     bind generic <esc>[1;5B scroll-line-down
	 * as without this change <c-down> can return a keycode value of 531
	 * (terminfo name kDN5), which is larger than KEY_MAX and has no
	 * pre-defined curses key name.
	 * NOTE: this MUST be called before initscr() */
	use_extended_names(FALSE);
#endif
```
just BEFORE initscr() is called.

I just thought I'd mention it.  If you want I can create a PR to remove the keyok() loop and use this instead ?
thx,
-m

**Comment by koutcher** [comment]
It is much cleaner indeed. Why 20081102 ? `NCURSES_EXT_FUNCS` macro was only made visible in ncurses v5_6_20071117 while `use_extended_names` appeared in v4_2_990301, so using `#ifdef NCURSES_VERSION` instead would allow the last CentOS 5 users to also benefit from the PR.

**Comment by mckellygit** [comment]
Ok sure, NCURSES_VERSION is good - I just used an old version thinking it was old enough.
I should have copied the same macro name you used before.
I'll create a PR

**Comment by mckellygit** [comment]
Created https://github.com/jonas/tig/pull/1074

**Pull request closed without merging**
